Fix bug - Short circuit when no dependabot alerts exist!
advanced-security/dependabot-epss-action pull request #4
Opened 2024-07-04 13:09 UTC by leonsparrowJM

This is a fix for:

SecDevOps---CondaDependabot Dependabot CVEs Count: 0
ForEach-Object: /home/runner/work/_actions/advanced-security/dependabot-epss-action/v0/action.ps1:136
Line |
 136 |  …  = $Dependabot_Alerts_CVEs | ForEach-Object { $epssHash[$_] } | Where …
     |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Index operation failed; the array index evaluated to null.
Error: Process completed with exit code 1.

To stop the process from erroring out if no CVEs exist.

2024-07-04 13:11 UTC, leonsparrowJM commented
addresses #3

2024-07-04 13:54 UTC, felickz requested changes
I think the big assumption I put into the code was a dependabot alert has a CVE .. that is not always true and may create an object with one or more null values - have to do some further testing here to make sure that is handled

2024-07-04 14:23 UTC, leonsparrowJM commented
Aye, it would be nice to cover all the repos in our org with this safety check, some are very small repos.

2024-07-05 16:47 UTC, felickz approved these changes
> Aye, it would be nice to cover all the repos in our org with this safety check, some are very small repos.

Agreed!

2024-07-05 16:48 UTC, merged